version: '3'
services:
  project1:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_ENV: local
    ports:
      - "3002:3001"
    links:
      - database
    volumes:
     - .:/usr/src/app
     - /usr/src/app/node_modules
    depends_on:
      - database

  database:
    image: mongo
    volumes:
      - './data:/data/db'
    ports:
      - 27037:27017



  # app:
  #   container_name: project1
  #   restart: always
  #   build: .
  #   ports:
  #     - '8081:3000'
  #   depends_on:
  #     - database
  # database:
  #   container_name: database
  #   image: mongo
  #   ports:
  #     - '27018:27017'